### PR TITLE
CORE-21 Migrate /apps/webhooks schemas

### PR DESCRIPTION
**Pull request by ash3rz**
Re: versioning - It seems the version is currently `2.11.6-SNAPSHOT`, and it looks like the pattern is to update to the version without `-SNAPSHOT` after merging.  Let me know if this is incorrect.  I'll have PRs open for apps and terrain pointing to version `2.11.6`

### CODE REVIEW

**Review by slr71 — APPROVED** [review]
LGTM! :shipit:

**Review by psarando — APPROVED** [review]
LGTM :shipit:

**Comment by slr71** [comment]
Ah, yes, I usually update the version after merging. I've been avoiding pushing commits for a non-snapshot release directly to master because it causes a failed build in Jenkins. (Jenkins doesn't have permission to push a non-snapshot release to Clojars for us.) I usually do something like this:

- Clone the cyverse-de repository directly (publishing the library from a fork causes confusing links in Clojars)
- Change the version to the non-snaphsot version
- Commit the change
- Tag the commit with the version number
- Publish the changes to Clojars (let us know if you have questions about this)
- Change the version to the new snapshot version
- Commit that change.
- Push both commits to master at the same time.
- Push the tags to master.

**Comment by psarando** [comment]
By the way, this entire process can be handled for you with `lein release :patch`. We have docs on how to setup `lein` with `clojars` and gpg keys at https://gitlab.cyverse.org/core-sw/de-docs/blob/master/development/clojars-setup.md

**Comment by ash3rz** [comment]
Thanks for the reviews!

**Pull request merged**
